"""change not null status2

Revision ID: a66e0fdb4532
Revises: 268fcece2b5b
Create Date: 2023-07-15 17:44:21.371941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66e0fdb4532'
down_revision = '268fcece2b5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subjects', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
