"""try to add realtions

Revision ID: 3a9114347724
Revises: bcc765a26e41
Create Date: 2023-07-13 20:39:58.395185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9114347724'
down_revision = 'bcc765a26e41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
