"""add fk for new models

Revision ID: bcc765a26e41
Revises: af8d12d44847
Create Date: 2023-07-12 16:24:56.108030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc765a26e41'
down_revision = 'af8d12d44847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.UUID(), nullable=False))
    op.add_column('subjects', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('teachers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'user_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'subject_id')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'user_id')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###
