"""change default value to prio

Revision ID: 0a51f4e4abe8
Revises: e17ec0b46a86
Create Date: 2023-07-19 17:31:19.976144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a51f4e4abe8'
down_revision = 'e17ec0b46a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
