"""remove tasks_count for subject model

Revision ID: e17ec0b46a86
Revises: 745a20b1a454
Create Date: 2023-07-18 17:25:07.970252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17ec0b46a86'
down_revision = '745a20b1a454'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'tasks_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('tasks_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
