"""change not null status

Revision ID: 268fcece2b5b
Revises: bb328bebae86
Create Date: 2023-07-15 17:43:36.691325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268fcece2b5b'
down_revision = 'bb328bebae86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
