"""first normal migration after reinit

Revision ID: 266d55761105
Revises: 33089b483a0b
Create Date: 2023-07-10 22:41:50.536943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266d55761105'
down_revision = '33089b483a0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',

    )
    # ### end Alembic commands ###
