"""try to add table

Revision ID: 2aa6ad3f80f2
Revises: 46974c081e4e
Create Date: 2023-06-21 20:10:51.762608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa6ad3f80f2'
down_revision = '46974c081e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
