"""try to add table

Revision ID: 30d759987d81
Revises: 2aa6ad3f80f2
Create Date: 2023-06-21 20:21:54.810179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d759987d81'
down_revision = '2aa6ad3f80f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
