"""first migration after reinit

Revision ID: 33089b483a0b
Revises: 
Create Date: 2023-07-10 22:33:54.743014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33089b483a0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
