"""DataBase TableCreation

Revision ID: 46974c081e4e
Revises: a286e744d64f
Create Date: 2023-06-21 20:00:53.620387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46974c081e4e'
down_revision = 'a286e744d64f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
