"""rename and refactor user model

Revision ID: abef9702fd64
Revises: 9649489b7c4a
Create Date: 2023-07-02 20:57:27.341633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abef9702fd64'
down_revision = '9649489b7c4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
